# Generated by Django 5.1.15 on 2026-03-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('patroni_port', models.IntegerField(default=8008)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=5432)),
                ('username', models.CharField(max_length=128)),
                ('db_name', models.CharField(default='postgres', max_length=255)),
                ('_encrypted_password', models.BinaryField(db_column='encrypted_password')),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('qa', 'QA'), ('pre-prod', 'Pre-Production'), ('prod', 'Production')], max_length=10)),
                ('ha_enabled', models.BooleanField(default=False)),
                ('is_up', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, default='unknown', max_length=20)),
                ('pg_version', models.CharField(blank=True, default='', max_length=50)),
                ('os_version', models.CharField(blank=True, default='', max_length=100)),
                ('ram_mb', models.IntegerField(blank=True, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_instances', to='inventory.application')),
                ('ha_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='inventory.hagroup')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
                ('can_login', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=list)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_users', to='inventory.postgresqlinstance')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='inventory.postgresqlinstance')),
            ],
        ),
        migrations.AddIndex(
            model_name='postgresqlinstance',
            index=models.Index(fields=['hostname'], name='inventory_p_hostnam_4ee8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='postgresqlinstance',
            index=models.Index(fields=['environment'], name='inventory_p_environ_f64bba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postgresqlinstance',
            unique_together={('ip_address', 'port')},
        ),
        migrations.AlterUniqueTogether(
            name='databaseuser',
            unique_together={('instance', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='databaseinfo',
            unique_together={('instance', 'name')},
        ),
    ]
