# Generated by Django 5.1.15 on 2026-03-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgresqlinstance',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
    ]
